# popclip (maybe you need to change the icons ğŸ˜‚)
name:
  en: Markdown List
  zh-Hans: Markdown åˆ—è¡¨
  zh-Hant: Markdown åˆ—è¡¨
  ja: Markdown ãƒªã‚¹ãƒˆ
version: 1
identifier: xyz.phpz.popclip.extension.markdown-list
icon: symbol:list.bullet
requirements: [text, paste]
actions:
  - title:
      en: Numbered List
      zh-Hans: ç¼–å·åˆ—è¡¨
      zh-Hant: ç·¨è™Ÿåˆ—è¡¨
      ja: ç•ªå·ä»˜ããƒªã‚¹ãƒˆ
    icon: symbol:list.number
    javascript: return '1. ' + popclip.input.text.replace(/\n/g, '\n1. ')
    after: paste-result
  - title:
      en: Bulleted List
      zh-Hans: æ— åºåˆ—è¡¨
      zh-Hant: æ— åºåˆ—è¡¨
      ja: æ— åºãƒªã‚¹ãƒˆ
    icon: symbol:list.bullet
    javascript: return '- ' + popclip.input.text.replace(/\n/g, '\n- ')
    after: paste-result